version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: carappdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./script/data:/var/data

  backend:
    build: .
    image: carapp-backend
    # image: mz12container.azurecr.io/sample/carapp-backend:latest
    ports:
      - "8080:8080"
    environment:
      - DB_CONNECT_STRING=jdbc:postgresql://db:5432/carappdb
      - DB_USER_NAME=postgres
      - DB_USER_PASSWORD=postgres
    depends_on:
      - db

volumes:
  pgdata:
